id: IC871613D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:23:57+00:00'
last_modified: '2022-06-08T06:31:49.304216+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017120
  title: བོད་ལུགས་གསོ་རིག་ཚིག་མཛོད་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9332':
      image_group_id: I00EGS1017132
      title: ''
      total_pages: 1276
      order: 1
      base_file: 9332.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
